### ISSUE TITLE
Le nombre de drapeaux n'est pas limité ET le nombre de drapeaux ne diminue pas.

### ISSUE THREAD

**Issue by Paul-Crp** [EmaCerez/HAX815X_Minesweeper#3]
![image](https://user-images.githubusercontent.com/24491338/226283794-863847d8-4038-4554-8ade-7201c63ec851.png)

**Comment by Paul-Crp** [comment]
Le nombre de drapeaux diminue maintenant, en passant du commentaire en vrai code

**Comment by EmaCerez** [comment]
Fixed
